---
layout: page
title: "PDF를 데이터로 보는 올바른 자세"
subtitle: "PDF2HTML"
author:
- name: "이광춘"
  affiliation: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
date: "`r Sys.Date()`"
tags: ["데이터 과학", "Data Science", "데이터 사이언스", "PDF", "글꼴", "Font", "폰트", "한국R컨퍼런스", "HTML"]
output:
  html_document: 
    include:
      after_body: footer.html
      before_body: header.html
    theme: default
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
bibliography: bibliography_pdf.bib
csl: biomed-central.csl
mainfont: NanumGothic
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')
```




# PDF 데이터 {#pdf-data}

`BrailleR`는 점자타자기를 의미하는 영어로 [`BrailleR`](https://github.com/ajrgodfrey/BrailleR) 팩키지에 시각장애인을 위한 다양한 도구들이 포함되어 있다.

- realmeter_2021년11월2주정례차기대선조사.pdf
- GallupKoreaDailyOpinion_471(20211105).pdf


```{r pdf2html, eval = FALSE}
library(tidyverse)
library(BrailleR)

BrailleR::pdf2html("realmeter_2021년11월2주정례차기대선조사.pdf")

# Your system is using Python 3.8.8
# 
# Traceback (most recent call last):
#   File "<string>", line 1, in <module>
# ModuleNotFoundError: No module named 'pdfminer'
# Your system is using Python 3.8.8
# 
# Traceback (most recent call last):
#   File "<string>", line 1, in <module>
# ModuleNotFoundError: No module named 'pdfminer'
# Collecting pdfminer
#   Downloading pdfminer-20191125.tar.gz (4.2 MB)
# Collecting pycryptodome
#   Downloading pycryptodome-3.11.0-cp35-abi3-win_amd64.whl (1.8 MB)
# Building wheels for collected packages: pdfminer
#   Building wheel for pdfminer (setup.py): started
#   Building wheel for pdfminer (setup.py): finished with status 'done'
#   Created wheel for pdfminer: filename=pdfminer-20191125-py3-none-any.whl size=6140113 sha256=61d6d58ab5db785d48ede1c47cffe67ff03028460a6ab97312fa6c45dcac1029
#   Stored in directory: c:\users\statkclee\appdata\local\pip\cache\wheels\1c\28\7d\f390b82bb0307deb63ff27a1474fd308ec68ee028cb9ab6283
# Successfully built pdfminer
# Installing collected packages: pycryptodome, pdfminer
# Successfully installed pdfminer-20191125 pycryptodome-3.11.0
# Traceback (most recent call last):
#   File "C:/Users/statkclee/Documents/R/win-library/4.0/BrailleR/Python/latin2html.py", line 131, in <module>
#     if __name__ == '__main__': sys.exit(main(sys.argv))
#   File "C:/Users/statkclee/Documents/R/win-library/4.0/BrailleR/Python/latin2html.py", line 126, in main
#     for line in fileinput.input(args):
#   File "C:\Users\statkclee\anaconda3\lib\fileinput.py", line 248, in __next__
#     line = self._readline()
#   File "C:\Users\statkclee\anaconda3\lib\fileinput.py", line 366, in _readline
#     self._file = open(self._filename, self._mode)
# FileNotFoundError: [Errno 2] No such file or directory: 'tempfile.html'
# Font size NA being turned into h1 
# Font size  being turned into  
# Warning messages:
# 1: In shell("python -c \"import pdfminer\"") :
#   'python -c "import pdfminer"' execution failed with error code 1
# 2: In shell("python -c \"import pdfminer\"") :
#   'python -c "import pdfminer"' execution failed with error code 1
# 3: In shell(paste0("python \"", file.path(system.file("Python/latin2html.py",  :
#   'python "C:/Users/statkclee/Documents/R/win-library/4.0/BrailleR/Python/latin2html.py" "tempfile.html" > "realmeter_2021년11월2주정례차기대선조사.html"' execution failed with error code 1
# 4: In file.remove("tempfile.html") :
#   cannot remove file 'tempfile.html', reason 'No such file or directory'
```

